name: flutter_movie_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  http: ^0.13.3
  dartz: ^0.9.2
  get_it: ^7.1.3
  pedantic: ^1.11.0
  google_fonts: ^2.0.0
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/
